backend:
  name: git-gateway
  branch: main

# For local development
# backend:
#   name: test-repo

media_folder: "src/images"
public_folder: "/images"

collections:
  - label: "Site Settings"
    name: "settings"
    files:
      - label: "General Settings"
        name: "general"
        file: "src/_data/settings.json"
        fields:
          - {label: "Site Name", name: "siteName", widget: "string"}
          - {label: "Tagline", name: "tagline", widget: "string"}
          - {label: "Contact Email", name: "contactEmail", widget: "string"}
          - label: "Regular Folk Dancing"
            name: "regularDancing"
            widget: "object"
            fields:
              - {label: "Show Regular Dancing Info", name: "enabled", widget: "boolean", default: true}
              - {label: "Schedule", name: "schedule", widget: "string", hint: "HTML allowed"}
              - {label: "Note Text", name: "note", widget: "string"}
          - label: "Camp Damp"
            name: "campDamp"
            widget: "object"
            fields:
              - {label: "Is Cancelled", name: "cancelled", widget: "boolean", default: false}
              - {label: "Cancellation Notice", name: "cancellationNotice", widget: "string", required: false}

  - name: "schedule"
    label: "Dance Schedule"
    folder: "src/content/schedule"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Time", name: "time", widget: "string", default: "7:30-10:30 PM"}
      - {label: "Location", name: "location", widget: "string", default: "St. Ann's Hall"}
      - {label: "Band", name: "band", widget: "string"}
      - {label: "Caller", name: "caller", widget: "string", required: false}
      - {label: "Cost", name: "cost", widget: "string", default: "$10"}
      - {label: "Description", name: "body", widget: "markdown", required: false}
      - {label: "Cancelled", name: "cancelled", widget: "boolean", default: false}

  - name: "locations"
    label: "Locations"
    folder: "src/content/locations"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Venue Name", name: "title", widget: "string"}
      - {label: "Address", name: "address", widget: "string"}
      - {label: "Map Link", name: "mapLink", widget: "string", required: false}
      - {label: "Regular Schedule", name: "schedule", widget: "string", required: false}
      - {label: "Description", name: "body", widget: "markdown", required: false}
      - {label: "Order", name: "order", widget: "number", default: 0, hint: "Lower numbers appear first"}

  - name: "links"
    label: "External Links"
    folder: "src/content/links"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Link Title", name: "title", widget: "string"}
      - {label: "URL", name: "url", widget: "string"}
      - {label: "Description", name: "description", widget: "string", required: false}
      - {label: "Category", name: "category", widget: "select", options: ["Dance Organizations", "Local Resources", "Other"], default: "Dance Organizations"}
      - {label: "Order", name: "order", widget: "number", default: 0, hint: "Lower numbers appear first"}

  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "src/_data/home.json"
        fields:
          - {label: "Hero Title", name: "heroTitle", widget: "string", default: "Welcome to Juneau Contras"}
          - {label: "Hero Subtitle", name: "heroSubtitle", widget: "text"}
          - label: "Feature Boxes"
            name: "features"
            widget: "list"
            max: 3
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Content", name: "content", widget: "text"}
              - {label: "Link Text", name: "linkText", widget: "string", required: false}
              - {label: "Link URL", name: "linkUrl", widget: "string", required: false}

      - label: "Camp Damp"
        name: "campdamp"
        file: "src/_data/campdamp.json"
        fields:
          - {label: "Page Title", name: "title", widget: "string", default: "Camp Damp"}
          - {label: "Event Dates", name: "dates", widget: "string"}
          - {label: "Location", name: "location", widget: "string"}
          - {label: "Description", name: "description", widget: "markdown"}
          - {label: "Registration Info", name: "registration", widget: "markdown"}

      - label: "More Info"
        name: "more"
        file: "src/_data/more.json"
        fields:
          - {label: "Page Title", name: "title", widget: "string", default: "More Information"}
          - {label: "Content", name: "content", widget: "markdown"}
          - {label: "Contact Section", name: "contactSection", widget: "markdown"}